# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            OpenPOTD
description:      'Welcome to the OpenPOTD landing page - here you can access the leaderboard, past questions with solutions, and a guide on how to get OpenPOTD bot set up on your own Discord server!'
url:              http://54.79.116.177/
baseurl:          /

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/poole/hyde

plugins:
    - jekyll-gist
    - jekyll-paginate
 
future: true
