# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Open POTD
description:      'Welcome to the OpenPOTD landing page!'
url:              http://54.79.116.177/
baseurl:          /

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/poole/hyde

plugins:
    - jekyll-gist
    - jekyll-paginate
    - jekyll-redirect-from
 
